code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension eamodio.gitlens
code --install-extension felipecaputo.git-project-manager
code --install-extension foxundermoon.shell-format
code --install-extension IBM.output-colorizer
code --install-extension lfs.vscode-emacs-friendly
code --install-extension mdschweda.vscode-granite-theme
code --install-extension miguelsolorio.min-theme
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension ms-vscode.cpptools
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension vangware.dark-plus-material
code --install-extension vscodevim.vim
code --install-extension webfreak.debug
code --install-extention bmewburn.vscode-intelephense-client
code --install-extention nickdodd79.gulptasks
code --install-extention bbenoist.vagrant
code --install-extention PKief.material-icon-theme
code --install-extention hdg.live-html-previewer
